package com.mozzartbet.stats.domain;

public enum IPayErrorCodeEnum {

	ERROR_CODE_OK,
	ERROR_CODE_ACCOUNT_BALANCE_TOO_LOW,
	ERROR_CODE_CLIENT_PARAMS_ERROR,
	ERROR_CODE_CLIENT_ACCESS_DENIED,
	ERROR_CODE_ACCOUNT_UNKNOWN,
	ERROR_CODE_ACCOUNT_EXPIRED,
	ERROR_CODE_OTHER,
	BAD_CAPTCHA,
	BAD_CAURRENCY,
	INCORRECT_PAYIN_AMOUNT_FOR_GROUPATION,
	INTERNAL_PROCESSING_ERROR;

}